### ISSUE TITLE
Error while setting up bibliotheek_be platform for sensor

### ISSUE THREAD

**Issue by tjorim** [myTselection/bibliotheek_be#1]
Installed latest commit master branch.
```
Logger: homeassistant.components.sensor
Source: custom_components/bibliotheek_be/utils.py:63
Integration: Sensor (documentation, issues)
First occurred: 11:47:50 AM (2 occurrences)
Last logged: 2:13:33 PM

Error while setting up bibliotheek_be platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bibliotheek_be/sensor.py", line 69, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/bibliotheek_be/sensor.py", line 44, in dry_setup
    await componentData._init()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 100, in _init
    self._user_details = await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bibliotheek_be/sensor.py", line 100, in <lambda>
    self._user_details = await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/config/custom_components/bibliotheek_be/utils.py", line 63, in login
    oauth_
NameError: name 'oauth_' is not defined
```

**Comment by myTselection** [comment]
sorry, I'm still figuring out the login/authentication. Nothing is working yet for this ;)

**Comment by myTselection** [comment]
A first working release is now available, feel free to test/comment. But please note it's still early beta version, so major changes might require a removal/recreation of the integration setup in future.

**Comment by tjorim** [comment]
Working great, thanks!
