### ISSUE TITLE
Update fails on AssertionError and AttributeError _userdetails

### ISSUE THREAD

**Issue by tjorim** [myTselection/bibliotheek_be#15]
First error:

```
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/bibliotheek_be/sensor.py:127
Integration: Bibliotheek.be (documentation, issues)
First occurred: 10:46:48 (2 occurrences)
Last logged: 11:46:48

Update for sensor.bibliotheek_be_jorim_tielemans_stuifzand fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/bibliotheek_be/sensor.py", line 179, in async_update
    await self._data.update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 149, in update
    await self._update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 146, in _update
    await self._force_update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 127, in _force_update
    assert self._userdetails is not None
AssertionError
```

And second error:

```
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/bibliotheek_be/sensor.py:183
Integration: Bibliotheek.be (documentation, issues)
First occurred: 10:47:18 (238 occurrences)
Last logged: 12:46:18

Update for sensor.bibliotheek_be_jorim_tielemans_stuifzand fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/bibliotheek_be/sensor.py", line 183, in async_update
    self._num_loans = self._data._userdetails.get(self._userid).get('loans').get('loans')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by myTselection** [comment]
I see the same from time to time, but it seems to auto-recover. So for now I'd expect it's backend related. After a reload all seems re-initiated correctly. So for now I'll close.
