### ISSUE TITLE
Error retrieving Library Details

### ISSUE THREAD

**Issue by github-vdabbeel** [myTselection/bibliotheek_be#20]
When trying to retrieve the library details, the site responds with a 301 redirect instead of a 200 code.
The structure of the details also seems to be different as just following the redirect results in a parsing error.

Parsing error when following the redirect
```
File "/config/custom_components/bibliotheek_be/utils.py", line 218, in library_details
    for dl in libraryArticle.find_all('dl',class_='library__date-open'):
              ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'
```

Debug log for the library details:
```
2023-10-22 14:26:10.581 DEBUG (SyncWorker_6) [custom_components.bibliotheek_be.utils] library details URL https://gent.bibliotheek.be/adres-en-openingsuren
2023-10-22 14:26:10.877 DEBUG (SyncWorker_6) [custom_components.bibliotheek_be.utils] bibliotheek.be library get result status code: 301
2023-10-22 14:26:10.878 DEBUG (SyncWorker_6) [custom_components.bibliotheek_be.utils] bibliotheek.be library get header: {'Date': 'Sun, 22 Oct 2023 12:26:10 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '466', 'Connection': 'keep-alive', 'x-redirect-id': '967', 'x-ua-compatible': 'IE=edge', 'content-language': 'nl', 'x-content-type-options': 'nosniff', 'location': 'https://gent.bibliotheek.be/adres-en-openingsuren/nieuw', 'age': '0', 'x-cache': 'MISS ausy-cultuurconnect-web8', 'x-cache-hits': '0', 'Front-End-Https': 'on'}
2023-10-22 14:26:10.879 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up bibliotheek_be platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bibliotheek_be/sensor.py", line 95, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/bibliotheek_be/sensor.py", line 44, in dry_setup
    await componentData._force_update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 147, in _force_update
    librarydetails = await self._hass.async_add_executor_job(lambda: self._session.library_details(libraryurl))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bibliotheek_be/sensor.py", line 147, in <lambda>
    librarydetails = await self._hass.async_add_executor_job(lambda: self._session.library_details(libraryurl))
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bibliotheek_be/utils.py", line 211, in library_details
    assert response.status_code == 200
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by TimBroddin** [comment]
Similar problem for Antwerp library:

```
2023-10-27 09:30:13.215 DEBUG (SyncWorker_8) [custom_components.bibliotheek_be.utils] library details URL https://antwerpen.bibliotheek.be/adres-en-openingsuren
2023-10-27 09:30:13.629 DEBUG (SyncWorker_8) [custom_components.bibliotheek_be.utils] bibliotheek.be library get result status code: 301
2023-10-27 09:30:13.630 DEBUG (SyncWorker_8) [custom_components.bibliotheek_be.utils] bibliotheek.be library get header: {'Date': 'Fri, 27 Oct 2023 07:30:13 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '482', 'Connection': 'keep-alive', 'x-redirect-id': '51', 'x-ua-compatible': 'IE=edge', 'content-language': 'nl', 'x-content-type-options': 'nosniff', 'location': 'https://antwerpen.bibliotheek.be/adressen-en-openingstijden', 'age': '0', 'x-cache': 'MISS ausy-cultuurconnect-web6', 'x-cache-hits': '0', 'Front-End-Https': 'on'}
2023-10-27 09:30:13.636 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up bibliotheek_be platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bibliotheek_be/sensor.py", line 95, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/bibliotheek_be/sensor.py", line 44, in dry_setup
    await componentData._force_update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 147, in _force_update
    librarydetails = await self._hass.async_add_executor_job(lambda: self._session.library_details(libraryurl))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bibliotheek_be/sensor.py", line 147, in <lambda>
    librarydetails = await self._hass.async_add_executor_job(lambda: self._session.library_details(libraryurl))
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bibliotheek_be/utils.py", line 211, in library_details
    assert response.status_code == 200
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by myTselection** [comment]
I didn't find an universal way to fetch the library details for these specific cases, but I tried now to continue without this optional info

**Comment by github-vdabbeel** [comment]
Thank you for the update. The integration is now working for me. I'm able to login and see the loaned books. 
For me the library details are not that important, so for me the issue can be closed and marked as solved if you want.

**Comment by TimBroddin** [comment]
Works for me too! Thanks a lot 🙏
