### ISSUE TITLE
Catch connection errors and ignore them

### ISSUE THREAD

**Issue by geertmeersman** [myTselection/bibliotheek_be#21]
Would be nice to catch the connection errors and ignore them (e.g. when the website of bibliotheek.be is not available or the internet connection is unavailable).

e.g.
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='bibliotheek.be', port=443): Read timed out. (read timeout=30)

**Comment by geertmeersman** [comment]
I also have a lot of these btw:

2024-01-04 10:39:21.335 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.bibliotheek_be_sofie_xxxxxxxxxxxxxxxxxx fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await self.async_update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 207, in async_update
    self._num_loans = self._data._userdetails.get(self._userid).get('loans').get('loans')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
