### ISSUE TITLE
Issue with loan_type 'Strip'

### ISSUE THREAD

**Issue by cvanfleteren** [myTselection/bibliotheek_be#23]
Update for sensor.bibliotheek_be_bib_kortrijk fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 898, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 322, in async_update
    self._loantypes[loan_item.get('loan_type')] += 1
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Strip'

**Comment by myTselection** [comment]
Thx for reproprting this! 
Should be fixed as of R1.6.8
