### ISSUE TITLE
Issue with fix for #23

### ISSUE THREAD

**Issue by cvanfleteren** [myTselection/bibliotheek_be#24]
Hi,

I updated to 1.6.8 after the fix for #23, but I get this error now

Update for sensor.bibliotheek_be_bib_kortrijk fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 898, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 323, in async_update
    self._loantype.setdefault(curr_loan_type, 0)
    ^^^^^^^^^^^^^^
AttributeError: 'ComponentLibrarySensor' object has no attribute '_loantype'

You probable meant 'self._loantypes' ?

**Comment by myTselection** [comment]
oeps, typo
