### ISSUE TITLE
Error retrieving Library Details (same as issue #20

### ISSUE THREAD

**Issue by github-vdabbeel** [myTselection/bibliotheek_be#27]
When trying to retrieve the library details, the site responds with a 301 redirect instead of a 200 code. This seems the be the same issue as in #20.
Currently using version 1.6.10

Here is the trace just to be complete:

```
2024-03-10 18:31:36.650 DEBUG (SyncWorker_10) [custom_components.bibliotheek_be.utils] library details URL https://gent.bibliotheek.be/adres-en-openingsuren
2024-03-10 18:31:36.872 DEBUG (SyncWorker_10) [custom_components.bibliotheek_be.utils] bibliotheek.be library get result status code: 301
2024-03-10 18:31:36.872 DEBUG (SyncWorker_10) [custom_components.bibliotheek_be.utils] bibliotheek.be library get header: Headers({'date': 'Sun, 10 Mar 2024 17:31:36 GMT', 'content-type': 'text/html; charset=UTF-8', 'content-length': '466', 'location': 'https://gent.bibliotheek.be/adres-en-openingsuren/nieuw', 'x-redirect-id': '967', 'content-language': 'nl', 'x-content-type-options': 'nosniff', 'age': '0', 'x-cache': 'MISS ausy-cultuurconnect-web8', 'x-cache-hits': '0', 'front-end-https': 'on'})
2024-03-10 18:31:36.874 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up bibliotheek_be platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/bibliotheek_be/sensor.py", line 96, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/bibliotheek_be/sensor.py", line 45, in dry_setup
    await componentData._force_update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 148, in _force_update
    librarydetails = await self._hass.async_add_executor_job(lambda: self._session.library_details(libraryurl))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bibliotheek_be/sensor.py", line 148, in <lambda>
    librarydetails = await self._hass.async_add_executor_job(lambda: self._session.library_details(libraryurl))
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bibliotheek_be/utils.py", line 233, in library_details
    assert response.status_code == 200
AssertionError
```

**Comment by myTselection** [comment]
thx for reporting! this is due the httpx for which the follow_redirect is set on global level and not per request. I don't have a library with redirected url's so not sure if the fix applied will fully work. Whenever a redirection location is returned, this will now be followed. Fixed in R1.6.11

**Comment by github-vdabbeel** [comment]
Can confirm, issue is fixed for me. All entities are populated again.
Just as an fyi, the integration is throwing an error that it's not able to fetch library details (as before). But that is not an issue for me.

**Comment by myTselection** [comment]
Ok thx for confirming.
Indeed some libraries have a very complex info site with info of multiple sub or related libraries. For those no details can be fetched...this will remain a known issue
