### ISSUE TITLE
Entities no longer being provided by the bibliotheek_be integration

### ISSUE THREAD

**Issue by BramDeBock** [myTselection/bibliotheek_be#28]
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:344
Integration: Sensor (documentation, issues)
First occurred: 1:21:01 PM (2 occurrences)
Last logged: 1:21:01 PM

Error while setting up bibliotheek_be platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bibliotheek_be/sensor.py", line 96, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/bibliotheek_be/sensor.py", line 45, in dry_setup
    await componentData._force_update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 129, in _force_update
    self._userdetails = await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bibliotheek_be/sensor.py", line 129, in <lambda>
    self._userdetails = await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bibliotheek_be/utils.py", line 84, in login
    assert response.status_code == 303
AssertionError

**Comment by myTselection** [comment]
Are you sure you are using the latest release? Issues similar to this have been fixed recently (R1.6.11)

**Comment by myTselection** [comment]
Or you want to check the provided username/password

**Comment by BramDeBock** [comment]
Apologies, checking my current version vs the latest available should've been a prerequisite prior to logging this issue. I updated the version and all is OK now! Thx.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
