### ISSUE TITLE
Update for sensor.bibliotheek_be*** fails - AssertionError

### ISSUE THREAD

**Issue by tjorim** [myTselection/bibliotheek_be#6]
```
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/bibliotheek_be/utils.py:88
Integration: Bibliotheek.be (documentation, issues)
First occurred: 12:45:48 AM (1 occurrences)
Last logged: 12:45:48 AM

Update for sensor.bibliotheek_be_jorim_tielemans_stuifzand fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 548, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_device_update
    raise exc
  File "/config/custom_components/bibliotheek_be/sensor.py", line 163, in async_update
    await self._data.update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 134, in update
    await self._update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 131, in _update
    await self._force_update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 113, in _force_update
    self._userdetails = await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bibliotheek_be/sensor.py", line 113, in <lambda>
    self._userdetails = await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/config/custom_components/bibliotheek_be/utils.py", line 88, in login
    assert response.status_code == 302
AssertionError
```

**Comment by tjorim** [comment]
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/bibliotheek_be/utils.py:57
Integration: Bibliotheek.be (documentation, issues)
First occurred: 1:25:59 AM (1 occurrences)
Last logged: 1:25:59 AM

Update for sensor.bibliotheek_be_jorim_tielemans_stuifzand fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/bibliotheek_be/sensor.py", line 179, in async_update
    await self._data.update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 149, in update
    await self._update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 146, in _update
    await self._force_update()
  File "/config/custom_components/bibliotheek_be/sensor.py", line 126, in _force_update
    self._userdetails = await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bibliotheek_be/sensor.py", line 126, in <lambda>
    self._userdetails = await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/config/custom_components/bibliotheek_be/utils.py", line 57, in login
    assert response.status_code == 302
AssertionError
