### ISSUE TITLE
Reload not working

### ISSUE THREAD

**Issue by tjorim** [myTselection/bibliotheek_be#8]
Installed version 0.4.0
When trying to reload I get the following error
I double checked by deleting the integration and setting it up again

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:166
First occurred: 9:29:32 PM (1 occurrences)
Last logged: 9:29:32 PM

Error setting up entry Bibliotheek.be for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 125, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 166, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

**Comment by myTselection** [comment]
hmm, strange. Can you delete the integration and and perform setup again after restart of HA?

**Comment by tjorim** [comment]
Setting up works fine, I choose reload on the integration page trying to force a refresh. Still getting this error.
